# Basic site settings
title: HalangdoN
description: >- 
  Mga himaya sa huna huna.
baseurl: "" # the subpath of your site, e.g. /blog or leave empty for root
url: "https://halangdon.github.io" # your site's base URL, e.g. https://username.github.io
twitter_username: jekyllrb
github_username: jekyll

# Build settings
plugins:
  - jekyll-feed

markdown: kramdown

collections:
  p:
    output: true


# Permalinks for posts and pages
# Note: The `permalink` setting for posts should be in individual pages/posts' front matter, not here in the config.
# Example for posts:
# permalink: /:year/:month/:day/:title/

# Optional: Default page layouts
defaults:
  - scope:
      path: "" # applies to all pages
    values:
      layout: "base" # Default layout for all pages (you can change this to `page` or any other layout)

